#!/bin/sh

# X config files
if [ -f $HOME/.Xmodmap ];then
    /usr/bin/xmodmap $HOME/.Xmodmap
fi
if [ -f $HOME/.Xresources ];then
    /usr/bin/xrdb -merge $HOME/.Xresources
fi
    
# screen 
xset dpms 600
xautolock -time 10 -locker "i3lock -i ~/.config/lock-wallpaper.png" &
if [ -f $HOME/.config/wallpaper.jpg  ];then
    feh --bg-scale $HOME/.config/wallpaper.jpg 
fi
unclutter -root -idle 5 &

# apps
run_keybase -a
odrive &
emacs --daemon &
recollindex -m -w 10

# keyring
gnome-keyring-daemon --start --components=secrets,pkcs11 >/dev/null


