#!/bin/sh

## Keyboard shortcuts
# echo -n "XSession Autostart... XBindkeys "
# if [ -f /usr/bin/xbindkeys -a -f "$HOME/.xbindkeysrc.noauto" ]; then
#    xbindkeys -f "$HOME/.xbindkeysrc.noauto" &
#    echo "ON"
# else
#    echo "OFF"
# fi

### Set X Keymap options for the Apple Magic Keyboard
#
# use right-option for Compose
# use Caps-Lock as another Control
# Swap left-option and left-command
# use right-win as Lv3-modifier (i.e. AltGr)
#
APPLEMAGIC=$HOME/config/xsession/setxkbmap.applemagic
PCUS=$HOME/config/xsession/setxkbmap.pcus
setxkbmap -config $APPLEMAGIC
