#!/bin/sh

## OfflineImap
echo -n "XSession Autostart... Recoll Index "

RCICMD=`which recollindex`

if [ "$?" = "0" -a -f ~/.recoll/recoll.conf ]; then
    recollindex -m -w 10
    echo "ON"
else
    echo "OFF"
fi

