#!/bin/sh

## Sage Math Environment
echo -n "XSession Autostart... SageMath Environment "
if [ x$SAGEMATH = "xyes" -a -f `which sage` ]; then
    export SAGE_BROWSER=$BROWSER
    sage -n $HOME/lavori/notebook open_viewer=False &
    echo "ON"
else
    echo "OFF"
fi

