#!/bin/sh

## Emacs Daemon

echo -n "XSession Autostart... Emacs Daemon "
if [ -f /usr/bin/emacs ]; then
    emacs --daemon &
    if [ -f /usr/bin/gconftool-2 ]; then
        gconftool-2 -s /desktop/gnome/url-handlers/org-protocol/command '/usr/bin/emacsclient %s' --type String
        gconftool-2 -s /desktop/gnome/url-handlers/org-protocol/enabled --type Boolean true
        echo "ON (gconf org-protocol YES)"
    else
        echo "ON (gconf org-protocol NO)"
    fi
else
    echo "OFF"
fi
