#!/bin/sh

## OfflineImap
echo -n "XSession Autostart... Offline IMAP "

OLICMD=`which offlineimap`

if [ "$?" = "0" -a -f ~/.offlineimaprc ]; then
    offlineimap &
    echo "ON"
else
    echo "OFF"
fi

